# Generated by Django 4.2.1 on 2023-05-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("typerevive", "0003_textbox_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="textbox",
            name="url",
        ),
        migrations.AddField(
            model_name="textbox",
            name="website",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="typerevive.website",
            ),
            preserve_default=False,
        ),
    ]
