# Generated by Django 4.2.1 on 2023-06-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typerevive", "0004_website_remove_textbox_url_textbox_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.CharField(),
        ),
    ]
